@echo off
setlocal EnableDelayedExpansion

REM ================================================================
REM  LogSense — Gemini Migration Setup Script
REM  Run this from the ROOT of your project:
REM  cd C:\path\to\LogSense-AI-Powered-Log-Intelligence-Platform
REM  setup.bat
REM ================================================================

echo.
echo  ╔══════════════════════════════════════════════════╗
echo  ║   LogSense — Gemini AI Migration Setup           ║
echo  ╚══════════════════════════════════════════════════╝
echo.

REM ----------------------------------------------------------------
REM  STEP 1 — Ask for Gemini API Key
REM ----------------------------------------------------------------
echo  [Step 1/5] Gemini API Key Setup
echo  Get your FREE key at: https://aistudio.google.com/app/apikey
echo  (No credit card needed — 15 req/min free quota)
echo.
set /p GEMINI_API_KEY="  Paste your Gemini API key (or press Enter to skip): "

if "%GEMINI_API_KEY%"=="" (
    echo  [WARN] No Gemini key provided. Gemini provider will be DISABLED.
    set GEMINI_ENABLED=false
) else (
    set GEMINI_ENABLED=true
    echo  [OK] Gemini enabled with model gemini-2.0-flash
)

REM ----------------------------------------------------------------
REM  STEP 2 — Ask for Ollama preference
REM ----------------------------------------------------------------
echo.
echo  [Step 2/5] Ollama Local Fallback Setup
set /p OLLAMA_CHOICE="  Enable Ollama local LLM fallback? (y/n, default=n): "

if /i "%OLLAMA_CHOICE%"=="y" (
    set OLLAMA_ENABLED=true
    set OLLAMA_BASE_URL=http://ollama:11434
    set OLLAMA_MODEL=llama3.2
    echo  [OK] Ollama enabled — will run as Docker service on port 11434
) else (
    set OLLAMA_ENABLED=false
    echo  [SKIP] Ollama disabled. Rule-based engine will act as final fallback.
)

REM ----------------------------------------------------------------
REM  STEP 3 — Write .env file
REM ----------------------------------------------------------------
echo.
echo  [Step 3/5] Writing .env file...

(
echo # ============================================================
echo # LogSense — AI Provider Configuration
echo # Generated by setup.bat
echo # ============================================================
echo.
echo # --- Gemini (Primary) ---
echo GEMINI_ENABLED=%GEMINI_ENABLED%
echo GEMINI_API_KEY=%GEMINI_API_KEY%
echo GEMINI_MODEL=gemini-2.0-flash
echo.
echo # --- Ollama (Fallback) ---
echo OLLAMA_ENABLED=%OLLAMA_ENABLED%
echo OLLAMA_BASE_URL=%OLLAMA_BASE_URL%
echo OLLAMA_MODEL=%OLLAMA_MODEL%
echo.
echo # --- Anthropic (DISABLED — no longer used) ---
echo ANTHROPIC_AI_ENABLED=false
echo ANTHROPIC_API_KEY=
echo.
echo # --- DB / Infra (defaults match docker-compose.yml) ---
echo DB_HOST=postgres
echo DB_PORT=5432
echo DB_NAME=logsense_rca
echo DB_USER=postgres
echo DB_PASS=postgres
echo KAFKA_BROKERS=kafka:9092
) > .env

echo  [OK] .env written successfully.

REM ----------------------------------------------------------------
REM  STEP 4 — Copy Java source files into project
REM ----------------------------------------------------------------
echo.
echo  [Step 4/5] Copying Java source files into rca-engine-service...

set SRC=rca-engine-service\src\main\java\com\logsense\rca
set RES=rca-engine-service\src\main\resources

REM Create package directories
mkdir "%SRC%\ai"      2>nul
mkdir "%SRC%\service" 2>nul
mkdir "%SRC%\model"   2>nul
mkdir "%RES%"         2>nul

REM ---- AI provider files ----
echo   Copying ai\AiProvider.java...
copy /Y "%~dp0ai\AiProvider.java"          "%SRC%\ai\AiProvider.java"          >nul 2>&1

echo   Copying ai\AiProviderException.java...
copy /Y "%~dp0ai\AiProviderException.java" "%SRC%\ai\AiProviderException.java" >nul 2>&1

echo   Copying ai\GeminiAiProvider.java...
copy /Y "%~dp0ai\GeminiAiProvider.java"    "%SRC%\ai\GeminiAiProvider.java"    >nul 2>&1

echo   Copying ai\OllamaAiProvider.java...
copy /Y "%~dp0ai\OllamaAiProvider.java"    "%SRC%\ai\OllamaAiProvider.java"    >nul 2>&1

echo   Copying ai\RuleBasedAiProvider.java...
copy /Y "%~dp0ai\RuleBasedAiProvider.java" "%SRC%\ai\RuleBasedAiProvider.java" >nul 2>&1

echo   Copying ai\AiProviderChain.java...
copy /Y "%~dp0ai\AiProviderChain.java"     "%SRC%\ai\AiProviderChain.java"     >nul 2>&1

REM ---- Service files ----
echo   Copying service\RcaEngineService.java...
copy /Y "%~dp0service\RcaEngineService.java" "%SRC%\service\RcaEngineService.java" >nul 2>&1

echo   Copying service\RcaPromptBuilder.java...
copy /Y "%~dp0service\RcaPromptBuilder.java" "%SRC%\service\RcaPromptBuilder.java" >nul 2>&1

REM ---- Model ----
echo   Copying model\AnomalyEvent.java...
copy /Y "%~dp0model\AnomalyEvent.java" "%SRC%\model\AnomalyEvent.java" >nul 2>&1

REM ---- application.yml ----
echo   Copying application.yml...
copy /Y "%~dp0application.yml" "%RES%\application.yml" >nul 2>&1

echo  [OK] All source files copied.

REM ----------------------------------------------------------------
REM  STEP 5 — Patch docker-compose.yml if Ollama enabled
REM ----------------------------------------------------------------
echo.
echo  [Step 5/5] Docker Compose...

if /i "%OLLAMA_ENABLED%"=="true" (
    echo  [INFO] Ollama is enabled.
    echo  [INFO] Add the following to your docker-compose.yml manually:
    echo.
    echo    ollama:
    echo      image: ollama/ollama:latest
    echo      ports: ["11434:11434"]
    echo      volumes: ["ollama_data:/root/.ollama"]
    echo      networks: [logsense-network]
    echo      entrypoint: ["/bin/sh", "-c", "ollama serve ^& sleep 5 ^&^& ollama pull llama3.2 ^&^& wait"]
    echo.
)

REM ----------------------------------------------------------------
REM  Summary
REM ----------------------------------------------------------------
echo.
echo  ╔══════════════════════════════════════════════════╗
echo  ║   Setup Complete — Summary                       ║
echo  ╚══════════════════════════════════════════════════╝
echo.
echo   AI Provider Chain:
if /i "%GEMINI_ENABLED%"=="true" (
    echo   [1] Gemini 2.0 Flash  ........  ENABLED  (Primary)
) else (
    echo   [1] Gemini            ........  DISABLED
)
if /i "%OLLAMA_ENABLED%"=="true" (
    echo   [2] Ollama (llama3.2) ........  ENABLED  (Fallback)
) else (
    echo   [2] Ollama            ........  DISABLED
)
echo   [3] Rule-Based Engine ........  ALWAYS ON (Backup)
echo.
echo   Next steps:
echo   1. docker-compose --env-file .env up -d
echo   2. Trigger anomaly: bash seed.sh
echo   3. Check RCA:  curl http://localhost:8083/api/v1/rca
echo   4. Dashboard:  http://localhost:3000
echo.

REM ----------------------------------------------------------------
REM  Optional: Start docker-compose now
REM ----------------------------------------------------------------
set /p START_NOW="  Start docker-compose now? (y/n): "
if /i "%START_NOW%"=="y" (
    echo.
    echo  Starting services...
    docker-compose --env-file .env up -d
    echo.
    echo  Waiting 30s for services to be ready...
    timeout /t 30 /nobreak >nul

    echo  Health checks:
    for %%p in (8081 8082 8083 8084 8085) do (
        curl -sf http://localhost:%%p/actuator/health >nul 2>&1
        if !errorlevel! == 0 (
            echo   Port %%p .... OK
        ) else (
            echo   Port %%p .... NOT READY (may still be starting)
        )
    )
    echo.
    echo  Open dashboard: http://localhost:3000
)

echo.
echo  Done. Press any key to exit.
pause >nul
endlocal
