package com.logplatform.alert.channel;

import com.logplatform.alert.model.Alert;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Slf4j
@RequiredArgsConstructor
public class EmailNotificationChannel implements NotificationChannel {

    private final JavaMailSender mailSender;

    @Value("${alert.email.enabled:false}")
    private boolean enabled;

    @Value("${alert.email.from:alerts@logplatform.com}")
    private String fromAddress;

    @Value("${alert.email.to:ops-team@company.com}")
    private String toAddress;

    @Override
    public void send(Alert alert) {
        if (!enabled) {
            log.debug("Email alerts disabled");
            return;
        }

        try {
            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom(fromAddress);
            message.setTo(toAddress);
            message.setSubject(String.format("[%s] %s Alert: %s",
                    alert.getSeverity(), alert.getAnomalyType(), alert.getServiceName()));
            message.setText(buildEmailBody(alert));

            mailSender.send(message);
            log.info("Email alert sent for alertId={}", alert.getId());
        } catch (Exception e) {
            log.error("Failed to send email alert for alertId={}: {}", alert.getId(), e.getMessage());
            throw new RuntimeException("Email send failed", e);
        }
    }

    private String buildEmailBody(Alert alert) {
        return String.format("""
                LOG INTELLIGENCE PLATFORM - ALERT NOTIFICATION
                ================================================
                
                Alert ID: %s
                Severity: %s
                Service:  %s
                Type:     %s
                Time:     %s
                
                Message:
                %s
                
                --
                This alert was auto-generated by the Log Intelligence Platform.
                Login to the dashboard to view full details and RCA report.
                """,
                alert.getId(),
                alert.getSeverity(),
                alert.getServiceName(),
                alert.getAnomalyType(),
                alert.getCreatedAt(),
                alert.getMessage()
        );
    }

    @Override
    public String channelName() {
        return "EMAIL";
    }

    @Override
    public boolean supports(Alert.AlertSeverity severity) {
        // Only email for HIGH and CRITICAL
        return severity == Alert.AlertSeverity.HIGH || severity == Alert.AlertSeverity.CRITICAL;
    }
}
