server:
  port: 8081

spring:
  application:
    name: log-ingestion-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/logplatform}
    username: ${SPRING_DATASOURCE_USERNAME:logplatform}
    password: ${SPRING_DATASOURCE_PASSWORD:logplatform123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topics:
    raw-logs: raw-logs
    error-logs: error-logs

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.logplatform: INFO
