server:
  port: 8081

spring:
  application:
    name: log-ingestion-service

  datasource:
    url: jdbc:postgresql://logplatform-postgres:5432/logplatform
    username: logplatform
    password: logplatform123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: logplatform-redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    raw-logs: raw-logs
    error-logs: error-logs

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.logplatform: INFO